-- =============================================
-- SUPERSEDED MIGRATION
-- =============================================
-- This older phase migration has been consolidated into:
--
--   supabase_production_patch.sql
--
-- Use the production patch for the current app. It includes duplicate-ball
-- protection, follower dedupe, notification dedupe, match-state alignment, and
-- the scorecard RPC expected by MatchDetailScreen.
