-- =============================================
-- SUPERSEDED MIGRATION
-- =============================================
-- This older phase migration has been replaced by:
--
--   supabase_production_patch.sql
--
-- Do not run the previous phase-2 version. It used quoted camelCase match
-- columns that do not match the current app/schema and had an outdated scoring
-- RPC shape. Keep this file as a breadcrumb for older notes, but use the
-- production patch for the current project.
